# ========================
# Stage 1: Build
# ========================
FROM alpine:3.22 AS builder

# 安装编译工具和 ldns
RUN apk add --no-cache build-base ldns-dev

# 复制源代码
WORKDIR /app
COPY /src ./src
COPY /include ./include

# 编译
RUN gcc -O2 -s -o ./docker-dns ./src/*.c \
    -I./include -lldns

# ========================
# Stage 2: Runtime
# ========================
FROM alpine:3.22

# 安装 ldns
RUN apk add --no-cache ldns \
    && rm -rf /var/cache/apk/*

# 拷贝二进制到运行镜像
COPY --from=builder /app/docker-dns /docker-dns

# 暴露 53/udp 端口
EXPOSE 53/udp

# 设置容器入口
ENTRYPOINT ["./docker-dns"]

CMD ["-f"]
