#!/bin/sh
# 中文语言文件

# docker-build.sh
LANG_ERROR_TAG_EMPTY="标签不能为空"
LANG_BUILDING_IMAGE="正在构建镜像..."
LANG_BUILD_COMPLETE="构建完成"
LANG_INITIALIZE_CONTAINER="正在初始化容器..."
LANG_COMPLETED="完成"

# docker-run.sh
# 通用术语
LANG_DEFAULT="默认"
LANG_CONFIGURED_PARAMS="已配置参数"
LANG_CONFIRM_DEPLOY="确认继续部署吗"
LANG_SELECT_OPERATION="请选择操作"
LANG_ENTER_CHOICE="请输入选择 [1-3]"

# 提示信息
LANG_ENTER_DOCKER_NET="请输入Docker网络名称"
LANG_ENTER_GATEWAY_IP="请输入网关IP地址"
LANG_ENTER_NETWORK_ADDR="请输入网络地址"
LANG_ENTER_RESOLV_PATH="请输入resolv路径"
LANG_ENTER_CONTAINER_NAME="请输入容器名称"
LANG_ENTER_IMAGE_NAME="请输入镜像名称"
LANG_ENTER_TIMEZONE="请输入时区名称或UTC±N格式"

# 配置项名称
LANG_DOCKER_NET="Docker网络名称"
LANG_GATEWAY_IP="网关IP地址"
LANG_NETWORK_ADDR="网络地址"
LANG_RESOLV_PATH="Resolv路径"
LANG_CONTAINER_NAME="容器名称"
LANG_IMAGE_NAME="镜像名称"
LANG_STD_TIMEZONE="标准时区"
LANG_POSIX_TIMEZONE="POSIX时区"

# 操作信息
LANG_STARTING_CONTAINER="正在启动容器..."
LANG_NETWORK_NOT_EXIST="Docker网络"
LANG_CREATING="不存在，正在创建..."
LANG_NETWORK_CREATED="Docker网络创建成功"
LANG_NETWORK_CREATE_FAILED="创建Docker网络失败"
LANG_NETWORK_EXISTS="Docker网络已存在"
LANG_SETTING_DNS="正在设置DNS服务器为"
LANG_DNS_ALREADY_CONFIGURED="DNS已正确配置，无需修改"
LANG_DNS_CONFIG_COMPLETED="DNS服务器配置完成"
LANG_CONTAINER_EXISTS="容器"
LANG_DELETE_REBUILD="删除并重建容器"
LANG_USE_NEW_NAME="使用新的容器名称"
LANG_EXIT="退出"
LANG_DELETING_OLD_CONTAINER="正在删除旧容器..."
LANG_ENTER_NEW_NAME="请输入新的容器名称"
LANG_NAME_CANNOT_BE_EMPTY="名称不能为空"
LANG_EXITING="正在退出"
LANG_EXITED="已退出"
LANG_CONTAINER_STARTED_SUCCESSFULLY="容器启动成功"

# 警告信息
LANG_WARN_UNKNOWN_TZ="警告：无法识别时区"
LANG_FALLBACK_UTC="将回退到UTC"
